### ISSUE TITLE
Laradock で環境構築

### ISSUE THREAD

**Issue by iQeda** [taichi-kobaya/portfolio#3]
Laradock で環境構築して、ポートフォリオを表示してください

**Comment by taichi-kobaya** [comment]
20210113_研修内容の、
Laradock の導入・設定

    mkdir laravel_study
    cd laravel_study
    git clone https://github.com/LaraDock/laradock.git
    cd laradock

を、

    mkdir taichi_portforio
    cd taichi_portforio
    git clone https://github.com/LaraDock/laradock.git
    cd laradock

に変更して手順通り行いました。
ディレクトリが/laravel_study/laradock/taichi_portforio/laradock となっているのですがこのまま進めてOKですか？

**Comment by iQeda** [comment]
`/laravel_study/laradock` はあくまで研修の環境構築ために作ったプロジェクトなので、それがポートフォリオの親フォルダになってるのは変な感じです。僕ならホームディレクトリあたりに別のディレクトリ作って中身を移しますね。
今回、自分だけが作業するフォルダなので場所はどこでもいいですが、チームで作業する場合にはディレクトリの場所も重要になるので覚えておいてください！
仮にこれが Google Drive の共有フォルダだったら、誰もそこにポートフォリオのプロジェクトがあるって分からない気がします。

**Comment by taichi-kobaya** [comment]
分かりました！ではホームディレクトリに別のディレクトリを作りたいと思います。

git rm taichi_portforio
でディレクトリ削除してホームディレクトリに新たに
mkdir taichi_portforio
作成する、という手順で合ってますか？

それとも/laravel_study/laradock配下に作ったディレクトリをそのまま移動できるんでしょうか？
ググったらWindowsバッチファイルでファイルやフォルダを移動させるmoveコマンドというのが出て来ましたがgit bashでは同コマンドについてのページは見つけられなかったもので。。。

**Comment by iQeda** [comment]
移動で出来ると思いますが、エラーが出たら作り直しでいいんじゃないですかね。
コマンドわからなかったら、エクスプローラーでドラッグアンドドロップでいいと思いますよ。
GitBsh (Linux コマンド) でやる場合は `mv` です。
コマンドプロンプト (Windows コマンド) は Linux コマンドと別物です。

**Comment by taichi-kobaya** [comment]
ありがとうございます！
デスクトップにMy_portfolioディレクトリを作って、taichi-portfolioディレクトリ、laradocディレクトリをそれぞれMy_portfolioディレクトリ直下の階層に配置しました。

ドキュメントルートについてですが、

ドキュメントルートとは、Webサーバ（HTTPサーバ）やFTPサーバが外部に公開するファイルなどが置かれたディレクトリ（フォルダ）。そのディレクトリにあるファイルと、下の階層にあるファイルやディレクトリが公開される。

という事は、

# ドキュメントルート設定
APP_CODE_PATH_HOST=../taichi-portfolio

で進めていけばOKでしょうか？

**Comment by iQeda** [comment]
はい、合っていると思います。あまり慎重にならなくても大丈夫ですよ。
とりあえずエラーが表示されたとか、上手く表示できなくなった、とかで進まなくなったら質問してみてくださいー

**Comment by taichi-kobaya** [comment]
承知しました！
早速ハマってしまったんですが、マイグレートファイル作成のコマンドを打ち込んだら以下のエラーが出て来ました。

Could not open input file: artisan

arisanファイルのあるディレクトリにいないことが原因と出て来ましたが、ここからどうすればいいのか分かりません。
VScodeでCtrl＋P検索すると、arisanファイルがあるのは

taichi_portfolio\portfolio\artisan

でした。

**Comment by iQeda** [comment]
@taichi-kobaya 
workspace コンテナに入ってないからですね

**Comment by taichi-kobaya** [comment]
workspace コンテナはlaradock内にあるものと思ってましたが間違ってますか？

Owner@LAPTOP-GP1VE0I7 MINGW64 ~/desktop/My_portfolio/laradock (master)
$ winpty docker-compose exec  workspace bash
root@d71a691b298b:/var/www# php artisan migrate
Could not open input file: artisan

**Comment by iQeda** [comment]
そもそも localhost で表示できていますか？
前回、ドキュメントルートにプロジェクトがなくてプロジェクトを移動させたりしましたが、それをまたやる必要があったりしませんか？

```sh
winpty docker-compose exec workspace bash
# プロジェクトがあるか確認
ls

cd [プロジェクト名]
php artisan migrate
```

**Comment by taichi-kobaya** [comment]
~/desktop/My_portfolio/laradockで上記解答の手順通りやったらマイグレーションファイルの作成は成功しました。

http://localhost/public/だとNot Foundになってしまいますが、
http://localhost/だとポートフォリオが表示されています。

**Comment by iQeda** [comment]
> http://localhost/だとポートフォリオが表示されています。

問題なさそうですね！おめでとうございます！
環境構築終わったみたいなので、当該 Issueはクローズしますね。
